name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalışır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Depoyu klonlar
      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake animasyonunu oluşturur
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Bugra-Ugur-Toygar
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Değişiklikleri pushlar
      - name: Push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

